### ISSUE TITLE
[Sample Application] Crash on Invalid Submission

### ISSUE THREAD

**Issue by ZKjellberg** [SandroMachado/openalpr-android#5]
When the user takes a bad picture, no results are returned, resulting in a NullPointerException crash.

```
Process: com.sandro.openalprsample, PID: 4146
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList org.openalpr.model.Results.getResults()' on a null object reference
   at com.sandro.openalprsample.MainActivity$2$1.run(MainActivity.java:104)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by SandroMachado** [comment]
Closed by https://github.com/SandroMachado/openalpr-android/commit/e1037941f4f7dba1bd74ef24b0833ccfd8fd6e18
