### ISSUE TITLE
[Sample Application] State Lost on Rotation

### ISSUE THREAD

**Issue by ZKjellberg** [SandroMachado/openalpr-android#6]
If the user rotates the screen, the image & result will be lost. I suggest retaining the state of at least the TextView result.

If the user rotates the screen while the request is being processed, it will result in a NullPointerException crash. This is similar to #5 except this may actually still have valid data as it is delayed until the processing finishes.

```
Process: com.sandro.openalprsample, PID: 4146
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.ArrayList org.openalpr.model.Results.getResults()' on a null object reference
  at com.sandro.openalprsample.MainActivity$2$1.run(MainActivity.java:104)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:148)
  at android.app.ActivityThread.main(ActivityThread.java:5417)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by SandroMachado** [comment]
Closed by #7.
